### ISSUE TITLE
NA direction values

### ISSUE THREAD

**Issue by aryam7** [beelabhmc/ant_tracker#10]
investigate lines [36-43@track.py](https://github.com/beelabhmc/ant_tracker/blob/386cc83874e6d993bce7d2ce84f957429c57f12c/track.py#L36) which determine the direction an ant is traveling
why are there so many NA values and what can be done it?

**Comment by aryam7** [comment]
add IDs to the output so that we can more easily track down any problems

**Comment by JarredAllen** [comment]
I'm closing this because the code has not used this method of direction determination since before I joined the project.
