### ISSUE TITLE
run pipeline on test video

### ISSUE THREAD

**Issue by aryam7** [beelabhmc/ant_tracker#14]
see if you can just run the tracking part (no need to split)

potential issues: clear background

play around with matlab tracking settings to see whether we can improve tracking
ex: reduce number of times ants can disappear but still be tracked
ex: edit blob size threshold so that we can distinguish ants in the foreground (from the background)

**Comment by mdonaldsonmatasci** [comment]
Not bounding box but blob size threshold. Is the tracked object large enough to be an ant in the foreground?

**Comment by aryam7** [comment]
ah ok I've fixed the issue above

**Comment by aryam7** [comment]
### test 1 results
ants seem to be tracked pretty well, even when they appear as small as in the test video.
in fact, matlab seems to be capable of tracking ants much smaller than this. it often mistakenly tracked the shadows of ants against the sides of the box (which are much smaller than the ants themselves)
unfortunately, ants underneath the bridge were also tracked

### test 1 next steps and potential fixes
cropping out the bridge will prevent matlab from tracking the ant shadows
as for ants that travel underneath the bridge, perhaps we could teach matlab what the shape of the bridge is? that way, it could identify when an ant is in one of the "holes" in the bridge and thus, make a decision about whether that ant is on the bridge or underneath it? this might even be possible with python alone using [opencv polyfill](https://docs.opencv.org/2.4/modules/core/doc/drawing_functions.html#fillpoly) to outline the bridge

**Comment by aryam7** [comment]
new plan: test a single segment of the bridge and manually verify that counts are correct

**Comment by aryam7** [comment]
### other problems identified
- pipeline missed ants that walked very fast
- pipeline could not make full tracks for ants that meet
- pipeline sometimes loses track of ants unexpectedly

**Comment by aryam7** [comment]
The work for this issue was continued in #18, so I'm closing it for now.
