### ISSUE TITLE
bridges at angles

### ISSUE THREAD

**Issue by aryam7** [beelabhmc/ant_tracker#4]
can we process rotated videos or crop at angles?
which might be better?

**Comment by aryam7** [comment]
this would indeed be possible, since we could project the routes onto a single axis
but turns out we don't need this, at least not right now

**Comment by mdonaldsonmatasci** [comment]
I think we might need it, will try to figure that out today

**Comment by JarredAllen** [comment]
As of 72ea769, this has been implemented. The code can now both crop and rotate ROIs, which are then handled by the tracking code normally.
