### ISSUE TITLE
np appending in antTracker

### ISSUE THREAD

**Issue by aryam7** [beelabhmc/ant_tracker#9]
each time antTracker processes a single video, it stores the results in a growing np array
at the end, it writes this entire array to disk all at once

it might be better if antTracker wrote its results immediately to disk each time it received them
- this will free up memory
- and make the script more robust to unexpected errors that might happen when it is processing any single video (since the other results won't be lost; they're already written disk)

**Comment by JarredAllen** [comment]
With converting to a pipeline, the video processing is separated to different function calls, so this issue has been resolved by commit 085775ef6a470b7bc4b694ca541eaf9013916780.
